# configs/rnd.yaml
env: coinrun
steps: 1000000
device: cuda
num_levels: 10

agent:
  num_envs: 8
  buffer_size: 200000
  batch_size: 64
  gamma: 0.99
  lr: 0.0001
  update_interval: 4
  target_update_freq: 1000
  int_coef: 0.25
